#Data Structure 

type animal {
	id: ID!  
	number: 12
  name: penguin 🐧
	food: fish 🐟
	home: [Antarctica]!   
}

type Antarctica {
    home: animal
    weather: subzero ❄️
}

# Arguments

type Starship {
  id: ID!
  name: Shark! #STRING
  length(unit: LengthUnit = METER): 8.5   #FLOAT
}

# Query and Mutation types

schema {
  query: Query
  mutation: Mutation
}

# QUERY
query {
  hero {
    name
  }
  droid(id: "2000") {
    name
  }
}

# Data retrieved : 
{
  "data": {
    "hero": {
      "name": "BB8"
    },
    "droid": {
      "name": "C-3PO"
    }
  }
}


type Query {
  hero(episode: Episode): BB8
  droid(id: ID!): C-3PO
}

type Mutation {
  hero(episode: Episode): R2-D2
  droid(id: ID!): C-3PO
}

